### PR TITLE
A few targeted Jekyll improvements

### PR DESCRIPTION
**Pull request by benbalter**
Long-time reader, first-time contributor. This PR includes a few targeted Jekyll improvements. I've made them as individual commits, in case you'd like to pick and choose. Specifically:

### Move `github-pages` to the `:jekyll_plugins` group

This helps set defaults and overrides locally to match what's used in production

### Use Jekyll feed to produce the RSS feed

Rather than use a bespoke template, use the crowd-tested plugin to generate the rss feed. They seem to be the same, other than the number of posts (and you'd then benefit from upstream improvements).

### Use Jekyll SEO Tag

This helps inject additional metadata into the header, with no additional action on your part, including Twitter cards, canonical URLs, next/previous URLs, and JSON-LD for richer indexing.

#### Main page before

```html
		<title>Mike McQuaid</title>
		<meta name="description" content="The home page for a software engineer named Mike McQuaid." />
		<meta name="author" content="Mike McQuaid" />
```

### Main page after

```html
<!-- Begin Jekyll SEO tag v1.3.3 -->
<title>Mike McQuaid - Mike McQuaid</title>
<meta property="og:title" content="Mike McQuaid" />
<meta name="description" content="The home page for a software engineer named Mike McQuaid." />
<meta property="og:description" content="The home page for a software engineer named Mike McQuaid." />
<link rel="canonical" href="http://mikemcquaid.com/" />
<meta property="og:url" content="http://mikemcquaid.com/" />
<meta property="og:site_name" content="Mike McQuaid" />
<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Mike McQuaid",
    "headline": "Mike McQuaid",
    "description": "The home page for a software engineer named Mike McQuaid.",
    "url": "http://mikemcquaid.com/"
  }
</script>
<!-- End Jekyll SEO tag -->
```

#### Post before

```html
		<title>Long-Distance Business Travel</title>
		<meta name="description" content="The home page for a software engineer named Mike McQuaid." />
		<meta name="author" content="Mike McQuaid" />
```

#### Post after

```html
<!-- Begin Jekyll SEO tag v1.3.3 -->
<title>Long-Distance Business Travel - Mike McQuaid</title>
<meta property="og:title" content="Long-Distance Business Travel" />
<meta name="description" content="One of the side effects of successfully finding a remote job and working from home is that you may find yourself having to travel internationally for work. In comparison to traveling for your own pleasure there’s a few attributes that may differ:" />
<meta property="og:description" content="One of the side effects of successfully finding a remote job and working from home is that you may find yourself having to travel internationally for work. In comparison to traveling for your own pleasure there’s a few attributes that may differ:" />
<link rel="canonical" href="http://mikemcquaid.com/2016/03/30/long-distance-business-travel/" />
<meta property="og:url" content="http://mikemcquaid.com/2016/03/30/long-distance-business-travel/" />
<meta property="og:site_name" content="Mike McQuaid" />
<meta property="og:type" content="article" />
<meta property="article:published_time" content="2016-03-30T00:00:00-04:00" />
<link rel="prev" href="http://mikemcquaid.com/2015/05/24/how-i-get-things-done/" title="How I Get Things Done" />
<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "BlogPosting",
    "headline": "Long-Distance Business Travel",
    "datePublished": "2016-03-30T00:00:00-04:00",
    "description": "One of the side effects of successfully finding a remote job and working from home is that you may find yourself having to travel internationally for work. In comparison to traveling for your own pleasure there’s a few attributes that may differ:",
    "url": "http://mikemcquaid.com/2016/03/30/long-distance-business-travel/"
  }
</script>
<!-- End Jekyll SEO tag -->
```

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Nice, liking these changes. With the RSS feed the issue I suspect is that I kinda have two Jekyll sites within one and the root RSS feed needs to only expose the articles (rather than `blog` posts) that the other one does. Thoughts?

**Comment by benbalter** [comment]
So confused. Got it. 

1. Copy/pasta the plugin template into a `atom.xml` file.

2. Probably better in the long run: Make the blog posts a collection (e.g., `blog_posts`) so they don't appear in `site.posts`.

**Comment by Haroenv** [comment]
Why didn't I know about `{% seo %}` before? I've always done that manually

**Comment by mikemcquaid** [comment]
> Probably better in the long run: Make the blog posts a collection (e.g., blog_posts) so they don't appear in site.posts.

@benbalter Ooo, that sounds like a good idea, didn't know what was a thing. Will give it a go.

**Comment by mikemcquaid** [comment]
> Probably better in the long run: Make the blog posts a collection (e.g., blog_posts) so they don't appear in site.posts.

@benbalter Cheers, did this in https://github.com/mikemcquaid/mikemcquaid.github.io/commit/96d99685f9fd1f7d1132996a07101ab8c36997b3 and I'm much happier with it than my previous hack.

**Comment by mikemcquaid** [comment]
Thanks for the PR @benbalter!

**Pull request merged**
